In [1]:
## Dependencies
import numpy as np

In [2]:
## Website analytics data:
## (row = day), (col = users, bounce, duration)
a = np.array([[815, 70, 115],
              [767, 80, 50],
              [912, 74, 77],
              [554, 88, 70],
              [1008, 65, 128]])

In [4]:
mean, stdev = np.mean(a, axis=0), np.std(a, axis=0)
# [811.2  76.4  88. ], [152.97764543   6.85857128  29.04479299]

In [3]:
print (a)

[[ 815   70  115]
 [ 767   80   50]
 [ 912   74   77]
 [ 554   88   70]
 [1008   65  128]]


In [5]:
print (mean)
print (stdev)

[811.2  75.4  88. ]
[152.97764543   7.98999374  29.04479299]


In [6]:
## One-liner
outliers = np.logical_and(np.abs(a[:,0] - mean[0]) > stdev[0],
                          np.abs(a[:,1] - mean[1]) > stdev[1],
                          np.abs(a[:,2] - mean[2]) > stdev[2])

In [8]:
np.abs(a[:,0])

array([ 815,  767,  912,  554, 1008])

In [9]:
mean

array([811.2,  75.4,  88. ])

In [10]:
np.shape(np.abs(a[:,0])-mean[0])


(5,)

In [15]:
np.abs(a[:,1]-47)


array([23, 33, 27, 41, 18])

In [7]:
print (outliers)

[False False False  True  True]


In [ ]:
## Result

print(a[outliers])